version: "3"
services:
  gd_traffic_proxy:
    image: gd_traffic_proxy
    ports:
      - "${HTTP_PROXY_PORT}:${HTTP_PROXY_PORT}"
    environment:
      - HTTP_PROXY_HOST=${HTTP_PROXY_HOST}
      - HTTP_PROXY_PORT=${HTTP_PROXY_PORT}
      - HTTP_PROXY_PREFIX=${HTTP_PROXY_PREFIX}
      - TARGET_SERVER_URL=${TARGET_SERVER_URL}
    restart: always
