import os

TARGET_SERVER_URL = os.environ["TARGET_SERVER_URL"]

HTTP_PROXY_HOST = os.environ["HTTP_PROXY_HOST"]
HTTP_PROXY_PORT = int(os.environ["HTTP_PROXY_PORT"])
HTTP_PROXY_PREFIX = os.environ["HTTP_PROXY_PREFIX"]
